/* **** Aamer Rehman Malik *****/
export const environment = {
  production: true,
  //UsersAPIURL: "http://localhost:51599/",
  //ReportsAPIURL: "https://localhost:44303/",
  //UsersAPIURL: "/core/",//"/core/",
  //ReportsAPIURL: "/core/",
  UsersAPIURL: "http://172.19.1.19:51599/",
  ReportsAPIURL: "http://172.19.1.19:44303/",
  AuthToken: "UserModel",
  RightsToken: "RightsModel",
  FormIDRemoveForTSPUser: [28, 77, 1121, 1125, 1127],
  FormIDRemoveForAllUsers: [1139, 1147],
  PrjTitle: "Punjab Skills Development Fund (PSDF)",
  PrjTitleShort: "PSDF",
  InActiveConfirmBoxTitle: "Active or Inactive this record",
  StatusConfirmBoxTitle: "Complaint status change this record",
  SaveMSG: "New ${Name} has been saved successfully",
  UpdateMSG: "${Name} has been Updated successfully",
  ActiveMSG: "${Name} enabled successfully",
  InActiveMSG: "${Name} disabled successfully",
  CancelMSG: "${Name} cancelled successfully",
  ActiveRTP: "${Name} created successfully",
  RemoveRTP: "${Name} removed successfully",
  CreateMSG: "${Name} created successfully",
  CustMSG: "${Name}",
  DateFormat: "dd/MM/yyyy",
  NewDateFormat: "dd/mm/yyyy",
  DateTimeFormat: "dd/MM/yyyy hh:mm:ss a",
  MonthFormat: "MM/yyyy",
  Decimal: "1.2-2",
  Mobile: "0000-0000000",
};
