export interface ITraineeProfile {
  TraineeID?: number;
  TraineeCode?: string;
  TraineeName?: number;
  TraineeCNIC?: number;
  FatherName?: number;
  GenderID?: number;
  GenderName?: string;
  TradeID?: number;
  TradeName?: string;
  SectionID?: number;
  SectionName?: string;
  DateOfBirth?: Date;
  CNICIssueDate?: Date;
  IsDual?: number;
  SchemeID?: number;
  SchemeName?: string;
  TSPID?: number;
  TSPName?: string;
  ClassID?: number;
  ClassCode?: string;
  TemporaryResidence?: string;
  PermanentResidence?: string;
  EducationID?: number;
  ContactNumber1?: string;
  ContactNumber2?: string;
  CNICVerified?: boolean;
  TraineeImg?: string;
  CNICImg?: string;
  TraineeAge?: number;
  ReligionID?: number
  VoucherHolder?: string;
  VoucherNumber?: string;
  VoucherOrganization?: string;
  WheredidYouHearAboutUs?: string;
  TraineeIndividualIncome?: string;
  HouseHoldIncome?: string;
  EmploymentStatusBeforeTrainingID?: number
  Undertaking?: boolean;
  GuardianName?: string;
  GuardianContactNo?: string;
  TraineeHouseNumber?: string;
  TraineeStreetMohalla?: string;
  TraineeMauzaTown?: string;
  TraineeDistrictID?: number
  TraineeTehsilID?: number
  AgeVerified?: boolean;
  DistrictVerified?: boolean;
  TraineeVerified?: boolean;
  NextToKinName?: string;
  NextToKinContactNo?: number
  IsManual?: boolean;
  IsExtra?: boolean;
  IsSubmitted: boolean;
  CNICImgNADRA: string;
  CNICUnVerifiedReason: string;
  AgeUnVerifiedReason: string;
  ResidenceUnVerifiedReason: string;
  CNICVerificationDate: string;
  ResultStatusID: number;
  UID: string;
  IsMigrated: boolean;
  TraineeStatusChangeDate: Date;
  TraineeStatusTypeID: number;
  TraineeStatusChangeReason: string;
  ResultStatusChangeDate: Date;
  ResultStatusChangeReason: string;
  TraineeRollNumber: string;
  TrainingAddressLocation: string;
  DistrictName: string;
}
